# Use official Node.js image as a base
FROM node:18

# Set working directory
WORKDIR /SWAPI-TEST

# Copy package files
COPY package*.json ./

# Copy all other application files
COPY . .

# Install dependencies
RUN npm install

# Build the TypeScript app
RUN npm run build

# Command to start the app
CMD ["npm", "start"]


# Expose the port the app runs on (e.g., 3000)
# EXPOSE 3000